samuelclay/NewsBlur

clients/ios/Classes/NBActivityItemProvider.m

[OriginalStoryViewController doOpenActionSheet] calls showSendTo with a nil
text parameter, but [NBActivityItemProvider activityViewController:
itemForActivityType:] returns a dictionary with the text as a value, and
dictionary literals can't use nil values. Use an empty string instead.
Appears to be a regression from 1002403e81087e16695589e7ad1b322856252d40.

Fix crash when mailing a URL in the original story view.

---

clients/android/NewsBlur/assets/dark_reading.css

When adding global shared stories I noticed that the table in blurblog stories showing "shared by..." wasn't readable when using the dark theme.
This tweaks the CSS to fix that.

Android: Fix background colour for blurblog share table in dark theme

---

clients/android/NewsBlur/res/layout/actionbar_custom_icon.xml
clients/android/NewsBlur/src/com/newsblur/activity/AllSharedStoriesItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/AllSharedStoriesReading.java
clients/android/NewsBlur/src/com/newsblur/activity/AllStoriesItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/AllStoriesReading.java
clients/android/NewsBlur/src/com/newsblur/activity/FeedItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/FeedReading.java
clients/android/NewsBlur/src/com/newsblur/activity/FolderItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/FolderReading.java
clients/android/NewsBlur/src/com/newsblur/activity/GlobalSharedStoriesItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/GlobalSharedStoriesReading.java
clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/Reading.java
clients/android/NewsBlur/src/com/newsblur/activity/ReadingAdapter.java
clients/android/NewsBlur/src/com/newsblur/activity/SavedStoriesItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/SavedStoriesReading.java
clients/android/NewsBlur/src/com/newsblur/activity/SocialFeedItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/SocialFeedReading.java
clients/android/NewsBlur/src/com/newsblur/network/APIManager.java
clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java
clients/android/NewsBlur/src/com/newsblur/util/UIUtils.java

Replaced the system ActionBar UI with one of our own so we can control the size of the icon in it.  Also added styling for the remaining reading types.
Also inclues a few little bugfixes found over the last week.
Mucking with the ActionBar can be tricky, so I would want to test this out on most of the Android versions we support, 11-22.  I've tested on 19 and 21 and will get 22 tonight.

Android: Custom ActionBar Styling (and Bugfixes)

---

templates/static/api.yml

I was looking through the API and I noticed that `/social/statistics/:user_id/:name` seems to stand out in regard to the similar endpoints around it.  The other endpoints follow a `/social/something/:user_id/:username` format and they all have a Tip that says "The `username` url parameter is optional. It's just recommended if you have it."
This led me to believe that maybe the `:name` url parameter was maybe just a typo, so here's a pull request that fixes it in case I'm correct in my thinking.

Fix :username typo in api.yml

---

clients/android/NewsBlur/proguard-project.txt

Added the necessary config so release builds will work with okhttp.

Fix release builds that use okhttp. (#680)

---

media/js/newsblur/models/stories.js

This is the issue referred to from https://getsatisfaction.com/newsblur/topics/does-not-open-links-in-new-tabs-in-various-webkit-browsers
Essentially, WebKit-based browsers on Linux can't handle the way NewsBlur attempts to open tabs in the background. This workaround detects those browsers and disables backgrounding for them.

Added a workaround for Linux webkit browsers

---

media/js/newsblur/models/stories.js

I screwed up the WebKit fix for Chrome/Safari. Here's a fix. Sorry about that.

Removed an unused variable that broke other browsers

---

clients/ios/Classes/EventWindow.m

Also makes delay-based contextual menu trigger work on 3D
Touch-capable devices (#781).

Make 3D Touch work to bring up contextual menus.

---

clients/ios/Classes/NewsBlurAppDelegate.m

(NSArrays cannot contain nil; finishMarkAsRead: already did this correctly.)

iOS: Fix crash marking story as unread if no story has been displayed yet.

---

apps/rss_feeds/models.py
apps/rss_feeds/tests.py
apps/rss_feeds/text_importer.py

fixed errors that happen when rss content has non-ASCII symbol or encoding is not utf-8.
e.g. cp1251 (windows cyrillic).

Text importer

---

clients/ios/Classes/FeedDetailViewController.m

The active story wasn't being set so this wasn't working.

iOS: Fix long-press story training from feed detail view.

---

clients/ios/Classes/OriginalStoryViewController.m

We need to implement the `WKUIDelegate` `webView:createWebViewWithConfiguration:forNavigationAction:windowFeature:` method to load those requests into the same WKWebView.
Also cleans some lingering `UIWebView` references.

Fix tapping on target=_blank links not working in the original story view

---

clients/ios/Classes/StoryDetailViewController.m

It missing a doc type, which was resulting in quirks mode being used. This affects font-size inheritance in tables and other rendering behavior.

Use standard mode in the story detail web view.

---

clients/ios/Classes/NBActivityItemProvider.m

After 1bbb0fc7e04b90c02305335db00d3ffc7fcf0905 the original URL is no longer included as a separate activity item, so we need to include it in the mail body directly.
Mailing from the story view directly not affected, there we include the URL in the text (done by NewsBlurAppDelegate's `showSendTo:withUrl:authorName:text:title:feedTitle:images:`)

Fix Mail action in "Send to" from the original story view not including the URL

---

templates/static/api.xhtml

I noticed this while reading the docs.

Fix typo on api docs

---

clients/android/NewsBlur/src/com/newsblur/activity/Reading.java

Making the unread-search behaviour match the web UI implementation.

Android: Change find-next-unread search order

---

clients/ios/Classes/TrainerViewController.m

This has been bugging me for a while; thought it was a NewsBlur bug.  I can't see how this would disturb anything if/when Apple were to fix the underlying issue.
Source of the workaround and more information at http://stackoverflow.com/questions/32685198/.

iOS: Work around iOS 9 issue where training menu doesn’t appear the first time you select text.

---

clients/android/NewsBlur/assets/reading.css

As discussed via e-mail this CSS change overrides min-width so newsletter text can wrap properly.
Tested across various other feeds with no obvious regressions.

Android: Fix newsletter text not wrapping

---

clients/android/NewsBlur/assets/dark_reading.css

With !important stripped these changes make the HTML based newsletters look reasonable.

Android: More dark theme improvements.

---

clients/android/NewsBlur/src/com/newsblur/activity/Main.java
clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java
clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java
clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java

Fixing a bug where stories (even prefetched/offline) can fail to load or may load into the wrong views when the device's network state is blackholed (not offline, but experiencing extreme timeouts).

Android: Fix loading of stories in bad network conditions

---

clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java

Very quick patch for an on-upgrade crash that is blocking release.  Will address a proper fix for this during the next cycle.

Android: Fix on-upgrade crash.

---

clients/android/NewsBlur/AndroidManifest.xml
clients/android/NewsBlur/res/layout/activity_init.xml
clients/android/NewsBlur/res/values/colors.xml
clients/android/NewsBlur/res/values/styles.xml
clients/android/NewsBlur/src/com/newsblur/activity/InitActivity.java
clients/android/NewsBlur/src/com/newsblur/util/AppConstants.java

Finally gave in and implemented some more strict on-upgrade checking.  Newer devices were launching the UI so quickly, sometimes the app would crash because the UI was trying to access the DB before it was upgraded.
There is now a splash screen when the app is opened the first time after install or upgrade while the check is occuring.  Total time from app start to the UI being displayed in full has actually stayed the same or gone down (time in the spash is == the time the UI used to pause with the "Tidying up" message), though being forced to use a spash might make it appear a bit slower due to some unfortunate cognitive biases.  Can't think of any more reliable way to finally squash the on-upgrade crashes, though.
Also disabled debug logging, since I expect this will be our final …

Android: Fix On-Upgrade Crashes

---

media/css/reader.css

In Firefox, opacity causes the background color underneath the container to pop through. By using filter instead, only the elements on top of background are affected.
In Chrome, they both have the same effect.

Switch to filter instead of opacity

---

clients/android/NewsBlur/src/com/newsblur/activity/AllStoriesItemsList.java

Fixed the place spotted in #938 where we have been using a totally wrong string asset.

fix weird old activity title casing issue found in #938

---

utils/feed_fetcher.py

- Send an Accept header asking for feed formats (instead of the current `*/*`)
- Don’t send A-IM without an If-None-Match or If-Modified-Since.
- Fixed Train-Case in “Accept-Encoding” header.

HTTP feed fetcher improvements

---

clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java

Matches web UI and fixes crash if either option was chosen with a social feed.

Android: Remove mute/unmute options for social feeds

---

clients/ios/Classes/NewsBlurAppDelegate.m
clients/ios/Resources/Settings.bundle/Root.plist
clients/ios/Resources/Settings.bundle/Root~ipad.plist

This can be tested by:
1. Installing Firefox iOS app on simulator https://github.com/mozilla-mobile/firefox-ios
2. Installing this PR on simulator
3. Running NewsBlur
4. In app preferences change story browser to Firefox
5. Go to story detail screen and tap on browser icon

Add Firefox to story browser list

---

clients/android/NewsBlur/res/menu/main.xml
clients/android/NewsBlur/res/values/strings.xml
clients/android/NewsBlur/src/com/newsblur/activity/Main.java
clients/android/NewsBlur/src/com/newsblur/activity/NbActivity.java
clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java
clients/android/NewsBlur/src/com/newsblur/fragment/ItemListFragment.java
clients/android/NewsBlur/src/com/newsblur/network/APIManager.java
clients/android/NewsBlur/src/com/newsblur/network/APIResponse.java
clients/android/NewsBlur/src/com/newsblur/network/domain/NewsBlurResponse.java
clients/android/NewsBlur/src/com/newsblur/service/CleanupService.java
clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java
clients/android/NewsBlur/src/com/newsblur/service/SubService.java
clients/android/NewsBlur/src/com/newsblur/service/UnreadsService.java
clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java
clients/android/NewsBlur/src/com/newsblur/util/Log.java
clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java

A super-lightweight logging interceptor to enable users send us logs on demand via email with no dependencies on any platform logging pipeline.  Enrolled any logging that might be relevant to our two open high-priority bugs that we cannot reproduce.
As soon as this gets to Beta, we can engage with users experiencing the bugs and have them send us some info that might help us resolve things.  It is crucial that we communicate to users that they send us a bug report as soon as they experience the bug, to ensure freshest data.  Wouldn't recommend pushing this all the way to Prod until it has been well smoke-tested in Beta.

Android: Bug Reporting / Log Capture Framework

---

clients/android/NewsBlur/AndroidManifest.xml
clients/android/NewsBlur/res/layout/row_feed.xml
clients/android/NewsBlur/res/menu/context_feed.xml
clients/android/NewsBlur/res/menu/feed_itemslist.xml
clients/android/NewsBlur/res/values/strings.xml
clients/android/NewsBlur/src/com/newsblur/activity/FeedItemsList.java
clients/android/NewsBlur/src/com/newsblur/activity/ReadingAdapter.java
clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java
clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java
clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java
clients/android/NewsBlur/src/com/newsblur/domain/Comment.java
clients/android/NewsBlur/src/com/newsblur/domain/Feed.java
clients/android/NewsBlur/src/com/newsblur/domain/Reply.java
clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java
clients/android/NewsBlur/src/com/newsblur/fragment/LoginProgressFragment.java
clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java
clients/android/NewsBlur/src/com/newsblur/fragment/SetupCommentSectionTask.java
clients/android/NewsBlur/src/com/newsblur/fragment/ShareDialogFragment.java
clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java
clients/android/NewsBlur/src/com/newsblur/network/APIManager.java
clients/android/NewsBlur/src/com/newsblur/network/domain/CommentResponse.java
clients/android/NewsBlur/src/com/newsblur/network/domain/NewsBlurResponse.java
clients/android/NewsBlur/src/com/newsblur/network/domain/StoriesResponse.java
clients/android/NewsBlur/src/com/newsblur/network/domain/UnreadCountResponse.java
clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java
clients/android/NewsBlur/src/com/newsblur/service/OriginalTextService.java
clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java
clients/android/NewsBlur/src/com/newsblur/util/Log.java
clients/android/NewsBlur/src/com/newsblur/util/ReadingAction.java
clients/android/NewsBlur/src/com/newsblur/util/UIUtils.java

* Proper fixes for the issues discovered with social features last month.  All social features should now be working as intended with a snappy local UX, full async/offline support, and immediate/intermediate/final state that matches the web UI.  Also added the missing functions for deleting and editing comments and replies.
* Fixed the broken no-focus-unreads explainer; added some logging to help us quickly diagnose user confusion about focus mode.
* Improved handling of stories with failed original text extraction. Now messages user and switches them back to a mode with content to view.
* Implemented insta-fetch for feeds. (#1032)
* Various non-critical bug fixes.
Should be ready for a week in Beta and then a week in 10% rollout, at least.

Android: Social Fixes, Insta-Fetch, Bugfixes

---

clients/ios/Classes/NewsBlurAppDelegate.m

There was a change to the Firefox iOS app where linking now requires a host of "open-url". This change broke linking to firefox from newsblur and this PR addresses the issue.
The corresponding code in Firefox is here: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Application/AppDelegate.swift#L393

Firefox Fix: change host to match Firefox iOS app change

---

apps/rss_feeds/icon_importer.py

This makes the fetcher work with the default ModSecurity ruleset, and would also avoid providing unsupported favicon formats (e.g. webp), by explictly preferring PNG and
x-icon formats.

favicon fetcher: provide an Accept header on requests.

---

clients/ios/Classes/NBActivityItemSource.m

Now Messages displays URL previews, just don’t include the title at all any more.
See https://getsatisfaction.com/newsblur/topics/app-share-sheet-duplicates-urls-shared.

iOS: Fix duplicate title/URL in Messages sharing.

---

media/css/reader.css

Fix for issue #1058. 
Needed to remove "display: -webkit-box", because "text-overflow: ellipsis" only works with "display: block".

Web: Changed whitespace break behavior in the feed title

---

docker-compose.yml

Mongo 3.4 does not work properly with pymongo, so pin the mongo docker image to v3.2.

Docker: Use mongo:3.2 docker image in docker-compose.

---

clients/android/NewsBlur/res/values/strings.xml
clients/android/NewsBlur/res/xml/activity_settings.xml
clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java
clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java
clients/android/NewsBlur/src/com/newsblur/util/PrefConstants.java
clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java

As discussed in #1065, a quick patch to make optional some meta-folders that have been causing a bad UX for some folks.

Android: Make Some Meta-Folders Optional

---

clients/ios/Classes/FolderTitleView.m
clients/ios/Classes/NewsBlurViewController.h
clients/ios/Classes/NewsBlurViewController.m

These indices are used in appDelegate.dictFoldersArray and as UIButton tags.
Removes a number of places where a number-to-name lookup was done for no apparent reason when the items are in appDelegate.dictFoldersArray already.
Fixes issue where all stories are now at index 3, not 2, and shift-E was showing infrequent site stories on iPad because the index was not updated when infrequent site stories were introduced.

iOS: Replace “magic number” 0-3 section indices with constants

---

docker/Dockerfile

Address issue #1113 by replacing `libmysqlclient-dev` with `default-libmysqlclient-dev`

Updating Dockerfile to use default-libmysqlclient-dev

---

docker-compose.yml

This PR does two things for using NewsBlur with docker-compose:
1. Importantly, this PR puts Redis (along with postgres, elasticsearch and mongo) on an internal-only network. This is especially important as by default Redis isn't using a password, and if you happen to have this on a public IP address, miscreants from around the world will mess with your Redis instance.
2. This PR also puts as volumes the remaining configs for the different backends.

Docker:  docker-compose: Add front/back networks and persistent config storage

---

.gitignore
config/redis.conf

This PR addresses the #1144 
It just avoids demonizing the redis service inside the container to hold it up.

Docker Compose Redis exits immediately

---

clients/android/NewsBlur/assets/light_reading.css

This fixes #1179 
The issue was due to the progressive rollout of dark mode. The fix uses the new `prefers-color-scheme` [CSS media query](https://developers.google.com/web/updates/2019/03/nic73) to bypass dark mode and prevent chromium from inverting the background.
It is based on v8.0.0 61eb724cbb682f67ef871bce66597632ad491cea , which is currently on the production track on Google Play, so it does not contain the beta features in v9b1.

ignore Chromium's dark mode settings

---

clients/android/NewsBlur/AndroidManifest.xml

As mentioned in #1178 this just bumps the Android API version so we can submit to Google Play.
It will be important to monitor potential performance issues, and quirks from the new jobs synchronization logic. I'll be watching those.

upgrade api version

---

clients/android/NewsBlur/assets/light_reading.css

chrome's dark mode updated to ignore the body tag, adding the html tag fixes it

ignore Chromium's dark mode settings, including html tag

---

clients/android/NewsBlur/res/values/theme.xml

this is to allow the holo theme to read the color value for places
where our themes do not touch, like menu text
This should resolve #1145

set primary text color globally

---

media/js/newsblur/views/story_titles_view.js

I've had trouble with Newsblur memory leaks for a long time, and recently Newsblur has been crashing its tab in Chrome multiple times a day. I tracked it down to this code. I'm not sure of the ultimate cause, but this seems to fix it for me (I have the preference set to false). I hope you can merge this and put it on the live site.

Disable stories loading animation (if preference), to avoid memory leak

---

clients/android/NewsBlur/src/com/newsblur/activity/Reading.java

android docs indicate that any system window can take focus from the activity, so we should not clear full screen in that case; the system will handle it if necessary (e.g. user leaves application, swipes navigation back up)
fixes #1200

remove clearing of fullscreen on window focus change

---

clients/android/NewsBlur/src/com/newsblur/util/StoryUtils.java

Fixes #1217 
For non-english languages, "today" and "yesterday" are non included for simplicity, since we don't have translation infrastructure in place beyond system provided formatting

use system formatted date for non-english locales

---

clients/android/NewsBlur/assets/reading.css

I think what was happening is that when a page loaded with a lot of content, the css styling could use sibling items to place images.
When an image alone was loaded, its width was being pushed outside the bounds of the parent by a single pixel, and the overflow style was to hide it.
This shifts the image to fit within the parent bounds.

modify css to not overflow images on chromium webview

---

clients/android/NewsBlur/src/com/newsblur/widget/ConfigureWidgetActivity.java

add the touch logic to the initial configuration.
Should fix the clicking issue.

add touch intent to widget initialization instead of only refresh

---

clients/ios/Classes/NewsBlurAppDelegate.m
clients/ios/Resources/Settings.bundle/Root.plist
clients/ios/Resources/Settings.bundle/Root~ipad.plist

This adds the option to use Microsoft Edge as the default browser in the iOS app, and is based on the existing logic for using the Opera browser.

Add Edge as a browser option

---

clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java

Setting the background to transparent also reduced one level of overdraw improving rendering speed

1302 Webview causing white flashes on dark theme

---

Makefile

Without it I get an error:
/bin/sh: 1: [[: not found
Which is ignored due to using leading dash `-` at https://github.com/samuelclay/NewsBlur/blob/3ad5295a33bb6fd469f8a64f0da6094656ad2da1/Makefile#L16
The same issue exists also in docker_django3.0

Makefile: specify SHELL bash

---

apps/reader/views.py

When retrieving the list of read stories from the server return the
last_read_date. This is useful for clients that re-downloaded stories
when performing a sync.
Unfortunately I am unable to figure out how to test this.
Signed-off-by: Alistair Francis <alistair@alistair23.me>

apps/reader/views: Send last_read_date when retrieving read stories

---

apps/push/models.py

The HTTP endpoint just redirects to HTTPS anyway, so let’s skip a redirect (clients may not even implement it?) and protect the integrity of the payload.

Move WebSub callbacks to HTTPS

---

apps/api/views.py

I got the following error when trying to save a story using the bookmarklet:
```
[Aug 27 05:16:33] Internal Server Error: /api/save_story/b76604da989d
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
return callback(request, *args, **kwargs)
File "/srv/newsblur/utils/view_functions.py", line 54, in wrapper
return self.view_wrapper(request, fn, *args, **kwargs)
File …
```

fix save_story endpoint

---

utils/feed_fetcher.py

The current implementation does not play well with longer durations than 60 seconds because the results of the divisions to obtain hours and minutes aren't floored before being multiplied.
Example:
- 3679 seconds is converted to '1.0219444444444445:00:00' instead of '1:01:19'
- I believe this is linked to [this forum topic](https://forum.newsblur.com/t/youtube-video-length/8860)

fix YouTube video duration calculation

---

apps/reader/views.py

This is a super simple fix for the problem I outlined in [this forum post](https://forum.newsblur.com/t/what-is-the-container-endpoint-middleware-used-to-connec-to-the-public-blurblog/9783). Instead of looking at the current host and checking to see if there is exactly 2 periods.. I am saying if there are 2 or more then just return the first split is presumed to be the sub (maybe sub sub) domain that we care about. 
It works for me with the NewsBlur being served at `news.mydomain.com`, but I could imagine this working with even more nested sub domains.. ¯\_(ツ)_/¯

fixes issues with subdomain hosting of user blurblogs

---

README.md

Hello,
I am a happy long time user of the iOS NewsBlur application. I wanted to add the Apple App Store badge to the `README.md` so that others know you can use NewsBlur on Apple mobile devices too.
Below is from the commit message
---
- Add a clickable badge for the NewsBlur Apple App Store page
- Use Apple's marketing website tool to get the App Store badge
- https://tools.applemediaservices.com/app/463981119
- Used HTML elements `&nbsp;` to add left padding to the Apple badge so that it aligns with the F-Droid badge. GitHub restricts what kind of inline styling is allowed in the README.md for security reasons. Inline styling of padding left is one of those attributes that get removed.
- https://github.com/github/markup#github-markup

Add Apple App Store badge to the README.md

---

docker/node/Dockerfile
node/original_text.coffee
node/original_text.js
node/package-lock.json
node/package.json

Node image to LTS 22.11.0
Chase rename of mercury-parser -> parser
npm update and npm audit fix
With this my instance running in docker (that I started using today) is able to start the `newsblur_node` container, no longer complains on all articles about being unable to get text of the story, and the Text view of feed entries works.

chore(node): update nodejs stuff

---

.cursor/rules/main.mdc

This pull request relocates the `.cursorrules` file to the new path `.cursor/rules/main.mdc` to align with the updated directory structure and naming conventions as per [Cursor docs](https://docs.cursor.com/context/rules#creating-a-rule).

Fix: move .cursorrules to .cursor/rules/main.mdc
