samuelclay/NewsBlur

clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/Main.java, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/database/FeedProvider.java, clients/android/NewsBlur/src/com/newsblur/fragment/ItemListFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/LoginProgressFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java, clients/android/NewsBlur/src/com/newsblur/service/ImagePrefetchService.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/service/SubService.java, clients/android/NewsBlur/src/com/newsblur/service/UnreadsService.java, clients/android/NewsBlur/src/com/newsblur/util/AppConstants.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java
A big round of testing and tweaks to go after known bugs and speed issues.  Good spot for a Beta candidate after basic light testing.
Please ensure you increment version strings before upgrading.
=> Android: Bugfixes and Lagfixes

clients/android/NewsBlur/res/layout/activity_settings.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/util/PrefConstants.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/VolumeKeyNavigation.java
Implements #653 
Since I was adding a preference I went for the three options: off, up = next or down = next.
=> Android: Volume key navigation

clients/android/NewsBlur/res/layout/activity_itemslist.xml, clients/android/NewsBlur/res/layout/row_loading_throbber.xml, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/fragment/ItemListFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/util/ImageCache.java, clients/android/NewsBlur/src/com/newsblur/util/NetworkUtils.java, clients/android/NewsBlur/src/com/newsblur/view/ProgressThrobber.java
Fixes for #582, #640, #664 as well as a few other minor bugs without issue numbers.
=> Android: Fixes for #582, #640, #664

config/requirements.txt
=> Bumping nltk to 2.0.5

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/src/com/newsblur/domain/Folder.java, clients/android/NewsBlur/src/com/newsblur/network/domain/FeedFolderResponse.java
Good catch. Ready for more testing.
=> Android: Fix crash in #679.

clients/ios/Classes/NewsBlurAppDelegate.m, clients/ios/Resources/Settings.bundle/Root.plist, clients/ios/Resources/Settings.bundle/Root~ipad.plist
While Safari and Chrome are decent enough browsers sometimes you want to use less bandwidth. So I added a way to set opera mini as the default browser as well.
=> Adding Opera Mini as an option for default browser.

clients/android/NewsBlur/res/layout/include_comment.xml
Fixing a resource that gets flagged as lint in the very newest AndroidStudio version.
=> Android: Fix Lint

clients/android/NewsBlur/src/com/newsblur/view/NewsblurWebview.java
Fixing the really broken link-clicking experience that is slowing spreading as users get the related system update.  Should make the update seamless if we get it out with this release.
=> Android: Ensure links in stories open in browser on all platforms. (#700)

clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/fragment/SetupCommentSectionTask.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ViewUtils.java
Fixing the two crashes that have been reported in beta and also the quick fullscreen upgrade.  
After a day or two of soaking this shouild probably go to prod, since #700 is spreading rapidly.
=> Android: Beta Bugs

clients/android/NewsBlur/res/menu/context_feed.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/fragment/DeleteFeedFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java
=> Android: Unfollow from long press menu

clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/activity/SocialFeedReading.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/fragment/ProfileActivityDetailsFragment.java
Hopefully a fix for #739. Would benefit from @dosiecki giving it a review and some wider testing.
=> Android: Fix #739

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/res/layout/activity_init.xml, clients/android/NewsBlur/res/layout/activity_reading.xml, clients/android/NewsBlur/res/layout/dialog_choosefolders.xml, clients/android/NewsBlur/res/layout/row_choosefolders.xml, clients/android/NewsBlur/res/menu/context_feed.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/InitActivity.java, clients/android/NewsBlur/src/com/newsblur/activity/Login.java, clients/android/NewsBlur/src/com/newsblur/activity/NbActivity.java, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java, clients/android/NewsBlur/src/com/newsblur/domain/Folder.java, clients/android/NewsBlur/src/com/newsblur/fragment/ChooseFoldersFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java
A few fixes and small tweaks for the Beta release, including a particularly irksome crash reported by quite a few of our testers.
=> Android: Beta Fixes

clients/ios/Classes/FeedDetailViewController.m
=> iOS: Don't scroll when going back to a story list (#832)

clients/ios/Classes/NBContainerViewController.h, clients/ios/Classes/NBContainerViewController.m, clients/ios/Classes/NewsBlurAppDelegate.m, clients/ios/Classes/StoryPageControl.m
After these fixes, my keyboard changes should be safe to merge (will rebase my branch on top of this shortly).
=> Fix regressions in #820

clients/android/NewsBlur/assets/reading.css, clients/android/NewsBlur/res/layout/activity_reading.xml, clients/android/NewsBlur/res/values/colors.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/fragment/RegisterProgressFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/network/APIResponse.java, clients/android/NewsBlur/src/com/newsblur/network/domain/FeedFolderResponse.java, clients/android/NewsBlur/src/com/newsblur/network/domain/RegisterResponse.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java
Fixes for two rare but nasty bugs found in the wild. Also includes a minor change so that everything looks pretty when #838 is resolved and some added logging that will go a long way towards future investigations.
=> Android: Bugfixes

apps/reader/views.py, apps/rss_feeds/icon_importer.py, apps/rss_feeds/models.py, media/js/newsblur/models/folders.js, utils/feed_fetcher.py, utils/feed_functions.py, utils/json_functions.py, utils/log.py
a bunch of unicode and utf-8 related fixes.
PEP8 fixes.
=> Unicode fixes

clients/ios/Classes/EventWindow.m
https://getsatisfaction.com/newsblur/topics/swiping-on-images-brings-up-image-menu-sometimes
=> iOS: Use force ratio instead of absolute force.

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/res/layout/activity_itemslist.xml, clients/android/NewsBlur/res/layout/include_comment.xml, clients/android/NewsBlur/res/menu/allstories_itemslist.xml, clients/android/NewsBlur/res/menu/feed_itemslist.xml, clients/android/NewsBlur/res/menu/itemslist.xml, clients/android/NewsBlur/res/menu/savedstories_itemslist.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java, clients/android/NewsBlur/src/com/newsblur/domain/Folder.java, clients/android/NewsBlur/src/com/newsblur/domain/Story.java, clients/android/NewsBlur/src/com/newsblur/fragment/ChooseFoldersFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/network/domain/FeedFolderResponse.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/service/UnreadsService.java, clients/android/NewsBlur/src/com/newsblur/util/AppConstants.java, clients/android/NewsBlur/src/com/newsblur/util/FeedSet.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java
Implements #745.  Also fixes a number of bugs in the current release.  
Good spot for a Beta.  Though most of the nastier bugs being fixed are limited to non-premium accounts, some of them are rather visible.
=> Android: Search and Bugfixes

templates/social/social_page.xhtml
eg. https://popular.global.newsblur.com
=> There is a cert mismatch on popular.global

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/Main.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/fragment/SetupCommentSectionTask.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ViewUtils.java
Fixes for a few issues discovered in the current Beta.
=> Android: Beta Bugfixes

clients/android/NewsBlur/assets/dark_reading.css
Improves readability of HTML heavy newsletters in dark theme.
=> Android: Dark theme improvements for newsletters.

clients/android/NewsBlur/src/com/newsblur/activity/Profile.java
This at least means that the interactions/activities lists reload.
=> Android: Save/restore userId in Profile activity (#891)

clients/android/NewsBlur/assets/dark_reading.css
Fix background of links in blockquotes for dark theme.
=> Android: More dark theme improvements.

clients/android/NewsBlur/BUILDING.md, clients/android/NewsBlur/build.gradle
Just a quick update to our build tips to reflect the changes we made in order to ensure our compatibility with the F-Droid folks.  So clean and compatible now!
=> Android: Updated Build Instructions

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java
Fixing some one-time on-upgrade crashes that we were seeing with the last few Betas.
=> Android: Fix on-upgrade crashes

clients/android/NewsBlur/res/drawable-nodpi/toggle_set_border.xml, clients/android/NewsBlur/src/com/newsblur/view/StateToggleButton.java
working around some ugly things resulting from buggy early implementations of the UI framework.
=> Android: Fix UI glitches on API 14 and 15 devices

clients/ios/Classes/StoryDetailViewController.m
This should fix the blank-story issue — that's been bugging me for weeks, but seeing complaints about it on Get Satisfaction tonight got me sufficiently motivated to fix it.
There's a lot of stuff in here I cleaned up that I don't completely understand (and its commit history is not terribly helpful). Maybe some of it is for old iOS versions? Please review and/or test!
=> Fix stories intermittently not displaying; clean up story loading

clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java, clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ReadingAction.java
As requested in #968 
Requires a database rebuild.
=> Android: Use ReadingAction for mute/unmute.

clients/android/NewsBlur/res/layout/fragment_loginregister.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/AddFacebook.java, clients/android/NewsBlur/src/com/newsblur/activity/AddTwitter.java, clients/android/NewsBlur/src/com/newsblur/fragment/LoginRegisterFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/service/SubService.java, clients/android/NewsBlur/src/com/newsblur/service/UnreadsService.java, clients/android/NewsBlur/src/com/newsblur/util/ImageLoader.java, clients/android/NewsBlur/src/com/newsblur/util/NotificationUtils.java, clients/android/NewsBlur/src/com/newsblur/util/PrefConstants.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/UIUtils.java
* Added a fix so users don't lose all of their state when the phantom-cookie bug hits.
* Implemented custom server endpoints.
* Rolled back the notification smoke test to work out some more bugs now that it has had some time to cook.
Should be good for quick beta and then release.
=> Android: Bugfixes, Custom Server Support

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java, clients/android/NewsBlur/src/com/newsblur/domain/Feed.java, clients/android/NewsBlur/src/com/newsblur/domain/Story.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/service/SubService.java, clients/android/NewsBlur/src/com/newsblur/service/UnreadsService.java, clients/android/NewsBlur/src/com/newsblur/util/ImageLoader.java, clients/android/NewsBlur/src/com/newsblur/util/NotificationUtils.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java
As described in #966, another incremental pass at building Android support for notifications.
=> Android: Second Notifications Alpha

README.md
Buttons with links to fdroid and google play store
=> Add two buttons to get the app

clients/android/NewsBlur/AndroidManifest.xml, clients/android/NewsBlur/res/menu/context_feed.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/res/xml/file_paths.xml, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/Main.java, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java, clients/android/NewsBlur/src/com/newsblur/database/DatabaseConstants.java, clients/android/NewsBlur/src/com/newsblur/domain/Feed.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/service/NBSyncService.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/NotificationUtils.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ReadingAction.java
Finishing up the notifications UI and fixing a number of bugs found in Beta 2.  Ready for Beta 3 any time!
=> Android: Bugfixes, Notifications

clients/android/NewsBlur/src/com/newsblur/fragment/ReadingFontDialogFragment.java
=> Android: Make reading font dialog sticky

clients/android/NewsBlur/src/com/newsblur/activity/InitActivity.java, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/fragment/AllSharedStoriesItemListFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java
A few very small bugs caught in Beta.  App should be ready for immediate release to Prod.
=> Android: Prod Release Candidate

clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java
as requested in #1066.
(sorry for brevity, made change from my phone)
=> swap infrequent and all rows

clients/android/NewsBlur/src/com/newsblur/database/FolderListAdapter.java
fixing the current bug in Prod
=> fix crash for users with no folders

utils/twitter_fetcher.py
Add "reply-to-self" tags to tweets where the author and "in reply to" user have the same id
=> Add "reply-to-self" tags to tweets

clients/ios/Classes/NBActivityItemSource.m
See e.g. https://twitter.com/acdha/status/956520307623383045.
=> iOS: Eliminate duplicate URL when sharing to Tweetbot.

media/js/newsblur/reader/reader.js
Update some sharing endpoints.
=> Share to HTTPS

apps/rss_feeds/models.py
After some digging I was able to find a workaround for broken tumblr rss feeds. I've verified that using this user agent does in fact work, at least for the time being.
=> Attempt to fix fetching tumblr rss feeds.

clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/InitActivity.java, clients/android/NewsBlur/src/com/newsblur/service/BootReceiver.java, clients/android/NewsBlur/src/com/newsblur/util/AppConstants.java, clients/android/NewsBlur/src/com/newsblur/util/NotificationUtils.java
This creates a Notification Channel which is required on 26+ to display notifications
It also uses the compatibility notification library
Related to #1178
=> Add Android 8.0 notification requirements

clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java
=> pass String to share chooser instead of Spannable

clients/android/NewsBlur/src/com/newsblur/database/BlurDatabaseHelper.java
=> don't include inactive feeds on unread count

clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java
=> add title to story sharing

clients/android/NewsBlur/res/layout/view_story_row.xml, clients/android/NewsBlur/res/values/dimens.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/res/xml/activity_settings.xml, clients/android/NewsBlur/src/com/newsblur/database/StoryViewAdapter.java, clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java, clients/android/NewsBlur/src/com/newsblur/util/PrefConstants.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ThumbnailStyle.java
=> add image thumbnail size preference

clients/android/NewsBlur/src/com/newsblur/activity/Main.java, clients/android/NewsBlur/src/com/newsblur/database/StoryViewAdapter.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java, clients/android/NewsBlur/src/com/newsblur/network/APIConstants.java, clients/android/NewsBlur/src/com/newsblur/network/APIManager.java, clients/android/NewsBlur/src/com/newsblur/util/FeedUtils.java, clients/android/NewsBlur/src/com/newsblur/util/ReadingAction.java
=> Set folder name as tag when saving a story

clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java
=> open system share dialog for links

clients/android/NewsBlur/res/menu/context_story_newest.xml, clients/android/NewsBlur/res/menu/context_story_oldest.xml, clients/android/NewsBlur/res/menu/story_context.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/FeedItemsList.java, clients/android/NewsBlur/src/com/newsblur/database/StoryViewAdapter.java, clients/android/NewsBlur/src/com/newsblur/fragment/FolderListFragment.java, clients/android/NewsBlur/src/com/newsblur/fragment/ReadingItemFragment.java
=> go to a feed from reading and list

clients/android/NewsBlur/assets/reading.css
=> image css modification test

clients/android/NewsBlur/res/layout/view_app_widget.xml, clients/android/NewsBlur/res/menu/menu_widget.xml, clients/android/NewsBlur/res/values/strings.xml, clients/android/NewsBlur/src/com/newsblur/activity/AllStoriesItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/ItemsList.java, clients/android/NewsBlur/src/com/newsblur/activity/Reading.java, clients/android/NewsBlur/src/com/newsblur/activity/WidgetConfig.java, clients/android/NewsBlur/src/com/newsblur/database/StoryViewAdapter.java, clients/android/NewsBlur/src/com/newsblur/fragment/ProfileActivityDetailsFragment.java, clients/android/NewsBlur/src/com/newsblur/util/PrefConstants.java, clients/android/NewsBlur/src/com/newsblur/util/PrefsUtils.java, clients/android/NewsBlur/src/com/newsblur/util/UIUtils.java, clients/android/NewsBlur/src/com/newsblur/util/WidgetBackground.java, clients/android/NewsBlur/src/com/newsblur/widget/WidgetProvider.java, clients/android/NewsBlur/src/com/newsblur/widget/WidgetRemoteViewsFactory.java, clients/android/NewsBlur/src/com/newsblur/widget/WidgetUtils.java
Fixing [loading issue](https://github.com/samuelclay/NewsBlur/pull/1320#issuecomment-640791190) and adding [widget transparent background](https://github.com/samuelclay/NewsBlur/pull/1320#issuecomment-641353172) option.
=> Android widget 3

apps/profile/views.py
Tested with Cypress [here](https://github.com/JasonGhent/NewsBlur/blob/cypress/Makefile), which will produce a video output:
=> Respect ENFORCE_SIGNUP_CAPTCHA in profile signup

docker-compose.yml
ref: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.16.3.html#release-notes-7.16.3
https://logging.apache.org/log4j/2.x/security.html
=> Update elasticsearch:7.16.3 (Log4j 2.17.1)
